export const LATERALIDADES = [
  { v: "", t: "— lateralidade —" },
  { v: "UD", t: "Unilateral direita" },
  { v: "UE", t: "Unilateral esquerda" },
  { v: "BL", t: "Bilateral" }
];

export const CATALOGO = [
  {c:"30501016", g:"Nariz", n:"Abscesso ou hematoma de septo nasal - drenagem"},
  {c:"30501024", g:"Nariz", n:"Abscesso ou hematoma de septo nasal - drenagem sob anestesia geral"},
  {c:"30501040", g:"Nariz", n:"Alongamento de columela"},
  {c:"30501059", g:"Nariz", n:"Biópsia de nariz"},
  {c:"30501067", g:"Nariz", n:"Corneto inferior - cauterização linear - unilateral"},
  {c:"30501075", g:"Nariz", n:"Corneto inferior - infiltração medicamentosa (unilateral)"},
  {c:"30501083", g:"Nariz", n:"Corpos estranhos - retirada em consultório (nariz)"},
  {c:"30501091", g:"Nariz", n:"Corpos estranhos - retirada sob anestesia geral / hospital"},
  {c:"30501474", g:"Nariz", n:"Corpos estranhos - retirada sob anestesia geral / hospital (nariz) - por videoendoscopia"},
  {c:"30501113", g:"Nariz", n:"Epistaxe - cauterização (qualquer técnica)"},
  {c:"30501121", g:"Nariz", n:"Epistaxe - cauterização da artéria esfenopalatina com microscopia - unilateral"},
  {c:"30501482", g:"Nariz", n:"Epistaxe - cauterização da artéria esfenopalatina com microscopia - unilateral por videoendoscopia"},
  {c:"30501130", g:"Nariz", n:"Epistaxe - cauterização das artérias etmoidais com microscopia - unilateral"},
  {c:"30501148", g:"Nariz", n:"Epistaxe - ligadura das artérias etmoidais - acesso transorbitário - unilateral"},
  {c:"30501164", g:"Nariz", n:"Epistaxe - tamponamento anterior"},
  {c:"30501156", g:"Nariz", n:"Epistaxe - tamponamento anteroposterior"},
  {c:"30501172", g:"Nariz", n:"Epistaxe - tamponamento anteroposterior sob anestesia geral"},
  {c:"30501180", g:"Nariz", n:"Exérese de tumor com abordagem craniofacial oncológica (tempo facial) pirâmide nasal"},
  {c:"30501199", g:"Nariz", n:"Exérese de tumor nasal por via endoscópica"},
  {c:"30501202", g:"Nariz", n:"Fechamento de fístula liquórica transnasal"},
  {c:"30501210", g:"Nariz", n:"Fístula liquórica - tratamento cirúrgico endoscópico intranasal"},
  {c:"30501229", g:"Nariz", n:"Fraturas dos ossos nasais - redução cirúrgica e gesso"},
  {c:"30501237", g:"Nariz", n:"Fraturas dos ossos nasais - redução incruenta e gesso"},
  {c:"30501245", g:"Nariz", n:"Imperfuração coanal - correção cirúrgica intranasal"},
  {c:"30501490", g:"Nariz", n:"Imperfuração coanal - correção cirúrgica intranasal por videoendoscopia"},
  {c:"30501253", g:"Nariz", n:"Imperfuração coanal - correção cirúrgica transpalatina"},
  {c:"30501261", g:"Nariz", n:"Ozena - tratamento cirúrgico"},
  {c:"30501504", g:"Nariz", n:"Ozena - tratamento cirúrgico por videoendoscopia"},
  {c:"30501270", g:"Nariz", n:"Perfuração do septo nasal - correção cirúrgica"},
  {c:"30501512", g:"Nariz", n:"Perfuração do septo nasal - correção cirúrgica por videoendoscopia"},
  {c:"30501288", g:"Nariz", n:"Polipectomia - unilateral"},
  {c:"30501296", g:"Nariz", n:"Reconstrução de unidade anatômica do nariz - por estágio"},
  {c:"30501300", g:"Nariz", n:"Reconstrução total de nariz - por estágio"},
  {c:"30501318", g:"Nariz", n:"Ressecção de tumores malignos transnasais"},
  {c:"30501326", g:"Nariz", n:"Rinectomia parcial"},
  {c:"30501334", g:"Nariz", n:"Rinectomia total"},
  {c:"30501342", g:"Nariz", n:"Rinoplastia reparadora"},
  {c:"30501350", g:"Nariz", n:"Rinosseptoplastia funcional"},
  {c:"30501520", g:"Nariz", n:"Rinosseptoplastia funcional por videoendoscopia"},
  {c:"30501369", g:"Nariz", n:"Septoplastia (qualquer técnica sem vídeo)"},
  {c:"30501539", g:"Nariz", n:"Septoplastia por videoendoscopia"},
  {c:"30501377", g:"Nariz", n:"Sinéquia nasal - ressecção unilateral - qualquer técnica"},
  {c:"30501385", g:"Nariz", n:"Tratamento cirúrgico da atresia narinária"},
  {c:"30501393", g:"Nariz", n:"Tratamento cirúrgico de deformidade nasal congênita"},
  {c:"30501407", g:"Nariz", n:"Tratamento cirúrgico do rinofima"},
  {c:"30501415", g:"Nariz", n:"Tratamento cirúrgico reparador do nariz em sela"},
  {c:"30501423", g:"Nariz", n:"Tratamento de deformidade traumática nasal"},
  {c:"30501431", g:"Nariz", n:"Tumor intranasal - exérese por rinotomia lateral"},
  {c:"30501440", g:"Nariz", n:"Tumor intranasal - exérese por via transnasal"},
  {c:"30501458", g:"Nariz", n:"Turbinectomia ou turbinoplastia - unilateral"},
  {c:"30501466", g:"Nariz", n:"Turbinoplastia por radiofrequência"},
  {c:"30502012", g:"Seios paranasais", n:"Angiofibroma - ressecção transmaxilar e/ou transpalatina"},
  {c:"30502020", g:"Seios paranasais", n:"Antrostomia maxilar intranasal"},
  {c:"30502292", g:"Seios paranasais", n:"Antrostomia maxilar intranasal por videoendoscopia"},
  {c:"30502284", g:"Seios paranasais", n:"Antrostomia maxilar, etmoidectomia etc a laser (abertura de todas as cavidades paranasais a laser)"},
  {c:"30502039", g:"Seios paranasais", n:"Artéria maxilar interna - ligadura transmaxilar"},
  {c:"30502306", g:"Seios paranasais", n:"Artéria maxilar interna - ligadura transmaxilar por videoendoscopia"},
  {c:"30502047", g:"Seios paranasais", n:"Cisto naso-alveolar e globular - exérese"},
  {c:"30502063", g:"Seios paranasais", n:"Descompressão transetmoidal do canal óptico"},
  {c:"30502071", g:"Seios paranasais", n:"Etmoidectomia externa"},
  {c:"30502080", g:"Seios paranasais", n:"Etmoidectomia intranasal"},
  {c:"30502314", g:"Seios paranasais", n:"Etmoidectomia intranasal por videoendoscopia"},
  {c:"30502098", g:"Seios paranasais", n:"Exérese de tumor com abordagem craniofacial oncológica seios (tempo facial)"},
  {c:"30502101", g:"Seios paranasais", n:"Exérese de tumor de seios paranasais por via endoscópica"},
  {c:"30502110", g:"Seios paranasais", n:"Fístula oro-antral - tratamento cirúrgico"},
  {c:"30502128", g:"Seios paranasais", n:"Fístula oronasal - tratamento cirúrgico"},
  {c:"30502136", g:"Seios paranasais", n:"Maxilectomia incluindo exenteração de órbita"},
  {c:"30502144", g:"Seios paranasais", n:"Maxilectomia parcial"},
  {c:"30502152", g:"Seios paranasais", n:"Maxilectomia total"},
  {c:"30502160", g:"Seios paranasais", n:"Pólipo antro-coanal de Killiam - exérese"},
  {c:"30502179", g:"Seios paranasais", n:"Punção maxilar transmeática ou via fossa canina"},
  {c:"30502187", g:"Seios paranasais", n:"Ressecção de tumor benigno"},
  {c:"30502195", g:"Seios paranasais", n:"Seios paranasais - biópsia qualquer via"},
  {c:"30502217", g:"Seios paranasais", n:"Sinusectomia frontal com retalho osteoplástico ou via coronal"},
  {c:"30502225", g:"Seios paranasais", n:"Sinusectomia fronto-etmoidal por via externa"},
  {c:"30502209", g:"Seios paranasais", n:"Sinusectomia maxilar - via endonasal"},
  {c:"30502322", g:"Seios paranasais", n:"Sinusectomia maxilar - via endonasal por videoendoscopia"},
  {c:"30502233", g:"Seios paranasais", n:"Sinusectomia maxilar - via oral (Caldwell-Luc)"},
  {c:"30502241", g:"Seios paranasais", n:"Sinusectomia transmaxilar (Ermiro de Lima)"},
  {c:"30502250", g:"Seios paranasais", n:"Sinusotomia esfenoidal"},
  {c:"30502349", g:"Seios paranasais", n:"Sinusotomia esfenoidal por videoendoscopia"},
  {c:"30502268", g:"Seios paranasais", n:"Sinusotomia frontal intranasal"},
  {c:"30502357", g:"Seios paranasais", n:"Sinusotomia frontal intranasal por videoendoscopia"},
  {c:"30502276", g:"Seios paranasais", n:"Sinusotomia frontal via externa"}
];